name: CITS-Continous Testing
on:
  issues:
    types:
    - opened
    - reopened
  workflow_dispatch:
    inputs:
      deploymentdata:
        description: Deployment data as a JSON object
        required: true
   
env:
    ENVIRONMENT_TO_EXECUTE: Default
   
jobs:
  build:
   
     runs-on: windows-latest
     steps:
     
     - uses: actions/checkout@v3
     - name: Setup Java 8
       uses: actions/setup-java@v3
       with:
          distribution: 'temurin'
          java-version: '8'
     - name: Setup Permissions
       run: chmod -R 755 ./
     - name: Run CITS Test
       run: ./Run.bat -run -project_location "Projects/Practice" -release "Release1" -testset "TestSet1" -browser "Chrome" -standaloneReport=true
     - name: Upload Results
       uses: actions/upload-artifact@v4
       with:
            name: Test Results
            path: Projects/Practice/Results/TestExecution/Release1/TestSet1/Latest